### ISSUE TITLE
Logo Proposal For EditCredit

### ISSUE THREAD

**Issue by iqbalhood** [Mostafa-MA-Saleh/EditCredit#2]
Hello Sir. I'm a UI/UX and Graphics Designer. 
I want propose a logo for your github project.
Would you mind if I propose logo for your application as my Open Source Contribution?

Thanks before.
Regards,
@iqbalhood

**Comment by Mostafa-MA-Saleh** [comment]
Sure, go right ahead.

**Comment by iqbalhood** [comment]
Hello sir,
These are my logo proposal for your application. If there any revision, please just tell it.
![edit credit](https://user-images.githubusercontent.com/1563756/42251413-6bf64a38-7f61-11e8-82f0-f211d151f6a8.jpg)

**Comment by Mostafa-MA-Saleh** [comment]
I think it looks perfect. I just wanna know if you have any specific request about attribution (specific links you would like me to include).

**Comment by iqbalhood** [comment]
Thanks for choosing my logo , Just insert my username @iqbalhood below the logo. :)
If you don't mind. I can edit the readme.md and make Pull Request to you.

**Comment by Mostafa-MA-Saleh** [comment]
That would be perfect, And thank you very much.
